language: php

php:
  - 7.2

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.3

addons:
  postgresql: '10'
  apt:
    packages:
      - postgresql-10-postgis-2.4
      - postgresql-10-postgis-2.4-scripts
      - postgresql-client-10
    
before_install:
  - sudo -u postgres psql -c "CREATE USER postgres WITH PASSWORD 'password'"
  - sudo -u postgres psql -c "ALTER ROLE postgres SUPERUSER"
install:
  - composer self-update && composer --version
  - pushd src/protected; composer install --prefer-dist --no-dev; popd

before_script:
  - gem install sass
  - npm install -g uglify-js uglifycss autoprefixer

script:
  - ./scripts/run-tests.sh
